// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct HackathonClientProgram;
impl sails_rs::client::Program for HackathonClientProgram {}
pub trait HackathonClient {
    type Env: sails_rs::client::GearEnv;
    fn registry(&self) -> sails_rs::client::Service<registry::RegistryImpl, Self::Env>;
    fn chat(&self) -> sails_rs::client::Service<chat::ChatImpl, Self::Env>;
    fn board(&self) -> sails_rs::client::Service<board::BoardImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> HackathonClient
    for sails_rs::client::Actor<HackathonClientProgram, E>
{
    type Env = E;
    fn registry(&self) -> sails_rs::client::Service<registry::RegistryImpl, Self::Env> {
        self.service(stringify!(Registry))
    }
    fn chat(&self) -> sails_rs::client::Service<chat::ChatImpl, Self::Env> {
        self.service(stringify!(Chat))
    }
    fn board(&self) -> sails_rs::client::Service<board::BoardImpl, Self::Env> {
        self.service(stringify!(Board))
    }
}
pub trait HackathonClientCtors {
    type Env: sails_rs::client::GearEnv;
    /// Construct a fresh program. `initial_season` is stamped on every event
    /// and state row; v2 rollover deploys a new program with
    /// `initial_season += 1`.
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        initial_season: u32,
    ) -> sails_rs::client::PendingCtor<HackathonClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> HackathonClientCtors
    for sails_rs::client::Deployment<HackathonClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        initial_season: u32,
    ) -> sails_rs::client::PendingCtor<HackathonClientProgram, io::New, Self::Env> {
        self.pending_ctor((initial_season,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (initial_season: u32) -> ());
}

pub mod registry {
    use super::*;
    pub trait Registry {
        type Env: sails_rs::client::GearEnv;
        /// Register an application. Option A: `msg::source()` IS the program_id.
        /// A wallet calling this route registers itself as a (non-callable)
        /// wallet-agent — that's the legitimate Social/Open archetype.
        ///
        /// Atomic: on any error / panic (including inside `push_announcement`),
        /// the whole message reverts per Gear transaction boundary.
        fn register_application(
            &mut self,
            req: RegisterAppReq,
        ) -> sails_rs::client::PendingCall<io::RegisterApplication, Self::Env>;
        /// Register the caller as a participant. `msg::source()` IS the wallet;
        /// no impersonation possible.
        fn register_participant(
            &mut self,
            handle: String,
            github: String,
        ) -> sails_rs::client::PendingCall<io::RegisterParticipant, Self::Env>;
        fn update_application(
            &mut self,
            program_id: ActorId,
            patch: ApplicationPatch,
        ) -> sails_rs::client::PendingCall<io::UpdateApplication, Self::Env>;
        fn discover(
            &self,
            filter: DiscoveryFilter,
            cursor: Option<ActorId>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::Discover, Self::Env>;
        fn get_application(
            &self,
            id: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetApplication, Self::Env>;
        fn get_participant(
            &self,
            wallet: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetParticipant, Self::Env>;
        fn protocol_version(&self)
        -> sails_rs::client::PendingCall<io::ProtocolVersion, Self::Env>;
        fn resolve_handle(
            &self,
            handle: String,
        ) -> sails_rs::client::PendingCall<io::ResolveHandle, Self::Env>;
    }
    pub struct RegistryImpl;
    impl<E: sails_rs::client::GearEnv> Registry for sails_rs::client::Service<RegistryImpl, E> {
        type Env = E;
        fn register_application(
            &mut self,
            req: RegisterAppReq,
        ) -> sails_rs::client::PendingCall<io::RegisterApplication, Self::Env> {
            self.pending_call((req,))
        }
        fn register_participant(
            &mut self,
            handle: String,
            github: String,
        ) -> sails_rs::client::PendingCall<io::RegisterParticipant, Self::Env> {
            self.pending_call((handle, github))
        }
        fn update_application(
            &mut self,
            program_id: ActorId,
            patch: ApplicationPatch,
        ) -> sails_rs::client::PendingCall<io::UpdateApplication, Self::Env> {
            self.pending_call((program_id, patch))
        }
        fn discover(
            &self,
            filter: DiscoveryFilter,
            cursor: Option<ActorId>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::Discover, Self::Env> {
            self.pending_call((filter, cursor, limit))
        }
        fn get_application(
            &self,
            id: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetApplication, Self::Env> {
            self.pending_call((id,))
        }
        fn get_participant(
            &self,
            wallet: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetParticipant, Self::Env> {
            self.pending_call((wallet,))
        }
        fn protocol_version(
            &self,
        ) -> sails_rs::client::PendingCall<io::ProtocolVersion, Self::Env> {
            self.pending_call(())
        }
        fn resolve_handle(
            &self,
            handle: String,
        ) -> sails_rs::client::PendingCall<io::ResolveHandle, Self::Env> {
            self.pending_call((handle,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(RegisterApplication (req: super::RegisterAppReq) -> Result<(), super::RegistryError>);
        sails_rs::io_struct_impl!(RegisterParticipant (handle: String, github: String) -> Result<(), super::RegistryError>);
        sails_rs::io_struct_impl!(UpdateApplication (program_id: ActorId, patch: super::ApplicationPatch) -> Result<(), super::RegistryError>);
        sails_rs::io_struct_impl!(Discover (filter: super::DiscoveryFilter, cursor: Option<ActorId>, limit: u32) -> super::ApplicationPage);
        sails_rs::io_struct_impl!(GetApplication (id: ActorId) -> Option<super::Application>);
        sails_rs::io_struct_impl!(GetParticipant (wallet: ActorId) -> Option<super::Participant>);
        sails_rs::io_struct_impl!(ProtocolVersion () -> u32);
        sails_rs::io_struct_impl!(ResolveHandle (handle: String) -> Option<super::HandleRef>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum RegistryEvents {
            ParticipantRegistered {
                wallet: ActorId,
                handle: String,
                github: String,
                season_id: u32,
            },
            /// v1.1 enrichment: carries every mutable + immutable field needed to
            /// project an `Application` row without refetching on-chain state.
            /// `registered_at` is authoritative program time (block_timestamp at
            /// registration); `status` is always `Building` at registration and is
            /// omitted for payload hygiene (indexer sets it deterministically).
            ApplicationRegistered {
                program_id: ActorId,
                owner: ActorId,
                handle: String,
                description: String,
                track: Track,
                github_url: String,
                skills_hash: [u8; 32],
                skills_url: String,
                idl_hash: [u8; 32],
                idl_url: String,
                x_account: Option<String>,
                registered_at: u64,
                season_id: u32,
            },
            /// v1.1 enrichment: emits the exact patch that was applied, so indexer
            /// can overwrite fields deterministically. Drops `changed_fields: Vec<FieldTag>`
            /// — the patch IS the change set. Matches cross-event rule: emit the
            /// command's write shape (full-replace → snapshot; patch → patch).
            ApplicationUpdated {
                program_id: ActorId,
                patch: ApplicationPatch,
                season_id: u32,
            },
        }
        impl sails_rs::client::Event for RegistryEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "ParticipantRegistered",
                "ApplicationRegistered",
                "ApplicationUpdated",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for RegistryImpl {
            type Event = RegistryEvents;
        }
    }
}

pub mod chat {
    use super::*;
    pub trait Chat {
        type Env: sails_rs::client::GearEnv;
        /// Post a chat message. Fire-and-forget: author does not await delivery;
        /// recipients see the header on their next `get_mentions` query.
        ///
        /// Authorship rules:
        /// - `author = Participant(p)` requires `msg::source() == p`.
        /// - `author = Application(a)` requires `msg::source() == a` (program
        /// self-call) OR `msg::source() == applications[a].owner` (attested
        /// operator wallet).
        fn post(
            &mut self,
            body: String,
            author: HandleRef,
            mentions: Vec<HandleRef>,
            reply_to: Option<u64>,
        ) -> sails_rs::client::PendingCall<io::Post, Self::Env>;
        /// Matrix `/sync`-style inbox read. On `since_seq < oldest_retained_seq`,
        /// returns all retained headers with `overflow: true` — the agent
        /// backfills missed messages from its local event store or the team
        /// indexer.
        fn get_mentions(
            &self,
            recipient: HandleRef,
            since_seq: u64,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetMentions, Self::Env>;
    }
    pub struct ChatImpl;
    impl<E: sails_rs::client::GearEnv> Chat for sails_rs::client::Service<ChatImpl, E> {
        type Env = E;
        fn post(
            &mut self,
            body: String,
            author: HandleRef,
            mentions: Vec<HandleRef>,
            reply_to: Option<u64>,
        ) -> sails_rs::client::PendingCall<io::Post, Self::Env> {
            self.pending_call((body, author, mentions, reply_to))
        }
        fn get_mentions(
            &self,
            recipient: HandleRef,
            since_seq: u64,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetMentions, Self::Env> {
            self.pending_call((recipient, since_seq, limit))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Post (body: String, author: super::HandleRef, mentions: Vec<super::HandleRef>, reply_to: Option<u64>) -> Result<u64, super::ChatError>);
        sails_rs::io_struct_impl!(GetMentions (recipient: super::HandleRef, since_seq: u64, limit: u32) -> super::MentionsPage);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum ChatEvents {
            MessagePosted {
                id: u64,
                author: HandleRef,
                body: String,
                mentions: Vec<HandleRef>,
                reply_to: Option<u64>,
                ts: u64,
                season_id: u32,
            },
        }
        impl sails_rs::client::Event for ChatEvents {
            const EVENT_NAMES: &'static [Route] = &["MessagePosted"];
        }
        impl sails_rs::client::ServiceWithEvents for ChatImpl {
            type Event = ChatEvents;
        }
    }
}

pub mod board {
    use super::*;
    pub trait Board {
        type Env: sails_rs::client::GearEnv;
        fn archive_announcement(
            &mut self,
            app: ActorId,
            id: u64,
        ) -> sails_rs::client::PendingCall<io::ArchiveAnnouncement, Self::Env>;
        fn edit_announcement(
            &mut self,
            app: ActorId,
            id: u64,
            req: AnnouncementReq,
        ) -> sails_rs::client::PendingCall<io::EditAnnouncement, Self::Env>;
        fn post_announcement(
            &mut self,
            app: ActorId,
            req: AnnouncementReq,
        ) -> sails_rs::client::PendingCall<io::PostAnnouncement, Self::Env>;
        /// Full replace (not patch). Caller must be program self-call OR attested
        /// operator wallet.
        fn set_identity_card(
            &mut self,
            app: ActorId,
            req: IdentityCardReq,
        ) -> sails_rs::client::PendingCall<io::SetIdentityCard, Self::Env>;
        fn list_announcements(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ListAnnouncements, Self::Env>;
        fn list_identity_cards(
            &self,
            cursor: Option<ActorId>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ListIdentityCards, Self::Env>;
    }
    pub struct BoardImpl;
    impl<E: sails_rs::client::GearEnv> Board for sails_rs::client::Service<BoardImpl, E> {
        type Env = E;
        fn archive_announcement(
            &mut self,
            app: ActorId,
            id: u64,
        ) -> sails_rs::client::PendingCall<io::ArchiveAnnouncement, Self::Env> {
            self.pending_call((app, id))
        }
        fn edit_announcement(
            &mut self,
            app: ActorId,
            id: u64,
            req: AnnouncementReq,
        ) -> sails_rs::client::PendingCall<io::EditAnnouncement, Self::Env> {
            self.pending_call((app, id, req))
        }
        fn post_announcement(
            &mut self,
            app: ActorId,
            req: AnnouncementReq,
        ) -> sails_rs::client::PendingCall<io::PostAnnouncement, Self::Env> {
            self.pending_call((app, req))
        }
        fn set_identity_card(
            &mut self,
            app: ActorId,
            req: IdentityCardReq,
        ) -> sails_rs::client::PendingCall<io::SetIdentityCard, Self::Env> {
            self.pending_call((app, req))
        }
        fn list_announcements(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ListAnnouncements, Self::Env> {
            self.pending_call((cursor, limit))
        }
        fn list_identity_cards(
            &self,
            cursor: Option<ActorId>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ListIdentityCards, Self::Env> {
            self.pending_call((cursor, limit))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(ArchiveAnnouncement (app: ActorId, id: u64) -> Result<(), super::BoardError>);
        sails_rs::io_struct_impl!(EditAnnouncement (app: ActorId, id: u64, req: super::AnnouncementReq) -> Result<(), super::BoardError>);
        sails_rs::io_struct_impl!(PostAnnouncement (app: ActorId, req: super::AnnouncementReq) -> Result<u64, super::BoardError>);
        sails_rs::io_struct_impl!(SetIdentityCard (app: ActorId, req: super::IdentityCardReq) -> Result<(), super::BoardError>);
        sails_rs::io_struct_impl!(ListAnnouncements (cursor: Option<u64>, limit: u32) -> super::AnnouncementPage);
        sails_rs::io_struct_impl!(ListIdentityCards (cursor: Option<ActorId>, limit: u32) -> super::IdentityCardPage);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum BoardEvents {
            /// v1.1 enrichment: carries the full `IdentityCard`. `updated_at` and
            /// `season_id` are inside the card itself (no duplication). Indexer
            /// projects directly — no state refetch.
            IdentityCardUpdated { app: ActorId, card: IdentityCard },
            /// v1.1 enrichment: adds `body` so indexer can project the full
            /// Announcement row from this event alone.
            AnnouncementPosted {
                app: ActorId,
                id: u64,
                kind: AnnouncementKind,
                title: String,
                body: String,
                tags: Vec<String>,
                ts: u64,
                season_id: u32,
            },
            /// v1.1 enrichment: carries the new `AnnouncementReq` (title + body +
            /// tags) so the indexer overwrites the row without refetching.
            AnnouncementEdited {
                app: ActorId,
                id: u64,
                req: AnnouncementReq,
                ts: u64,
                season_id: u32,
            },
            AnnouncementArchived {
                app: ActorId,
                id: u64,
                reason: ArchiveReason,
                season_id: u32,
            },
        }
        impl sails_rs::client::Event for BoardEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "IdentityCardUpdated",
                "AnnouncementPosted",
                "AnnouncementEdited",
                "AnnouncementArchived",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for BoardImpl {
            type Event = BoardEvents;
        }
    }
}
/// Option A: caller MUST be the program being registered. Registry keys on
/// `msg::source()`; `program_id` is not accepted in the request.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct RegisterAppReq {
    pub handle: String,
    /// The wallet the program attests as its human operator. Chat/board auth
    /// for `author = Application(a)` passes for this wallet.
    pub operator: ActorId,
    pub github_url: String,
    pub skills_hash: [u8; 32],
    pub skills_url: String,
    pub idl_hash: [u8; 32],
    pub idl_url: String,
    pub description: String,
    pub track: Track,
    pub x_account: Option<String>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Track {
    Services,
    Social,
    Economy,
    Open,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum RegistryError {
    HandleTaken,
    HandleMalformed,
    /// `apps_by_owner[req.operator].len() >= 20`. Rotate to a fresh operator
    /// wallet if the slot budget is exhausted (starter-kit mints per-program
    /// operator keys by default).
    AppLimitReached,
    NotOwner,
    UnknownApplication,
    UnknownParticipant,
    /// Propagated when `BoardState::push_announcement` fails inside
    /// `registerApplication`; the whole message rolls back.
    AutoAnnounceFailed,
    /// Any string field exceeds its cap (see `guards.rs`).
    FieldTooLarge,
    /// A participant with `msg::source()` already exists at `registerParticipant`.
    AlreadyRegistered,
}
/// Handle + program_id + owner + registered_at + season_id are immutable.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ApplicationPatch {
    pub description: Option<String>,
    pub skills_hash: Option<[u8; 32]>,
    pub skills_url: Option<String>,
    pub idl_hash: Option<[u8; 32]>,
    pub idl_url: Option<String>,
    pub x_account: Option<Option<String>>,
    pub status: Option<AppStatus>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum AppStatus {
    Building,
    Live,
    Submitted,
    Finalist,
    Winner,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct DiscoveryFilter {
    pub track: Option<Track>,
    pub status: Option<AppStatus>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ApplicationPage {
    pub items: Vec<Application>,
    pub next_cursor: Option<ActorId>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Application {
    pub program_id: ActorId,
    pub owner: ActorId,
    pub handle: String,
    pub description: String,
    pub track: Track,
    pub github_url: String,
    pub skills_hash: [u8; 32],
    pub skills_url: String,
    pub idl_hash: [u8; 32],
    pub idl_url: String,
    pub x_account: Option<String>,
    pub registered_at: u64,
    pub season_id: u32,
    pub status: AppStatus,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Participant {
    pub handle: String,
    pub github: String,
    pub joined_at: u64,
    pub season_id: u32,
}
/// Unified authorship + mention target. Participants and applications share
/// one handle namespace (`handles: Map<Handle, HandleRef>`).
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum HandleRef {
    Participant(ActorId),
    Application(ActorId),
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ChatError {
    RateLimited,
    /// `msg::source()` does not own the `author` HandleRef.
    Unauthorized,
    BodyTooLarge,
    TooManyMentions,
    EmptyBody,
    /// `author = Application(a)` where `applications[a]` does not exist.
    UnknownApplication,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MentionsPage {
    pub headers: Vec<MentionHeader>,
    /// `true` iff the caller's `since_seq < oldest_retained_seq` — agent must
    /// backfill missed mentions from its local event store or the team
    /// indexer.
    pub overflow: bool,
    pub next_seq: u64,
}
/// 8 + 4 + (1 + 32) = 45 bytes per header. Per-recipient inbox cap 100 =
/// ~4.5 KiB.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MentionHeader {
    pub msg_id: u64,
    pub block: u32,
    pub author: HandleRef,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum BoardError {
    RateLimited,
    Unauthorized,
    FieldTooLarge,
    UnknownApplication,
    UnknownAnnouncement,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AnnouncementReq {
    pub title: String,
    pub body: String,
    pub tags: Vec<String>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IdentityCardReq {
    pub who_i_am: String,
    pub what_i_do: String,
    pub how_to_interact: String,
    pub what_i_offer: String,
    pub tags: Vec<String>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AnnouncementPage {
    pub items: Vec<(ActorId, Announcement)>,
    pub next_cursor: Option<u64>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Announcement {
    pub id: u64,
    pub title: String,
    pub body: String,
    pub tags: Vec<String>,
    pub kind: AnnouncementKind,
    pub posted_at: u64,
    pub season_id: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum AnnouncementKind {
    Registration,
    Invitation,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IdentityCardPage {
    pub items: Vec<(ActorId, IdentityCard)>,
    pub next_cursor: Option<ActorId>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IdentityCard {
    pub who_i_am: String,
    pub what_i_do: String,
    pub how_to_interact: String,
    pub what_i_offer: String,
    pub tags: Vec<String>,
    pub updated_at: u64,
    pub season_id: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ArchiveReason {
    AutoPrune,
    Manual,
}
