// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct PricedAttestationClientProgram;
impl sails_rs::client::Program for PricedAttestationClientProgram {}
pub trait PricedAttestationClient {
    type Env: sails_rs::client::GearEnv;
    fn attest(&self) -> sails_rs::client::Service<attest::AttestImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> PricedAttestationClient
    for sails_rs::client::Actor<PricedAttestationClientProgram, E>
{
    type Env = E;
    fn attest(&self) -> sails_rs::client::Service<attest::AttestImpl, Self::Env> {
        self.service(stringify!(Attest))
    }
}
pub trait PricedAttestationClientCtors {
    type Env: sails_rs::client::GearEnv;
    /// Construct the program. `owner` will be the address authorized to call
    /// `SetFee` and `WithdrawFees` (next iteration). `flat_fee` is the per-call
    /// fee in plancks.
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        owner: ActorId,
        flat_fee: u128,
    ) -> sails_rs::client::PendingCtor<PricedAttestationClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> PricedAttestationClientCtors
    for sails_rs::client::Deployment<PricedAttestationClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        owner: ActorId,
        flat_fee: u128,
    ) -> sails_rs::client::PendingCtor<PricedAttestationClientProgram, io::New, Self::Env> {
        self.pending_ctor((owner, flat_fee))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (owner: ActorId, flat_fee: u128) -> ());
}

pub mod attest {
    use super::*;
    pub trait Attest {
        type Env: sails_rs::client::GearEnv;
        /// Issue an attestation. Caller must attach `msg::value() >= required_fee()`.
        ///
        /// Refund matrix (per `agent-starter/references/pricing.md`):
        /// - Underpayment      → `Err(InsufficientPayment)`,  full value refunded.
        /// - Self-loop         → `Err(SelfLoop)`,             full value refunded.
        /// - ArithmeticOverflow → `Err(ArithmeticOverflow)`,  full value refunded.
        /// - Success + overpay → `Ok(Receipt)`,               excess refunded.
        /// - Success + exact   → `Ok(Receipt)`,               no refund.
        ///
        /// Refunds are delivered via `CommandReply::with_value(...)` — the reply
        /// itself carries the refund. Per Gear/Sails semantics, a separate
        /// `msg::send_bytes` queued from a handler that returns `Err` does NOT
        /// fire (`gear-messaging-and-replies.md`: "outbound send and reply effects
        /// appear only after successful execution"). Bundling the refund into the
        /// reply is the canonical Sails pattern and works on both Err and Ok paths.
        fn issue(
            &mut self,
            subject: [u8; 32],
            kind: AttestationKind,
        ) -> sails_rs::client::PendingCall<io::Issue, Self::Env>;
        /// Pure read — total fees accepted via `Issue`. See state docs for the
        /// "accounting only, not chain balance" caveat.
        fn collected_fees(&self) -> sails_rs::client::PendingCall<io::CollectedFees, Self::Env>;
        /// Pure read — number of receipts issued so far.
        fn receipt_count(&self) -> sails_rs::client::PendingCall<io::ReceiptCount, Self::Env>;
        /// Pure read — current required fee.
        fn required_fee(&self) -> sails_rs::client::PendingCall<io::RequiredFee, Self::Env>;
    }
    pub struct AttestImpl;
    impl<E: sails_rs::client::GearEnv> Attest for sails_rs::client::Service<AttestImpl, E> {
        type Env = E;
        fn issue(
            &mut self,
            subject: [u8; 32],
            kind: AttestationKind,
        ) -> sails_rs::client::PendingCall<io::Issue, Self::Env> {
            self.pending_call((subject, kind))
        }
        fn collected_fees(&self) -> sails_rs::client::PendingCall<io::CollectedFees, Self::Env> {
            self.pending_call(())
        }
        fn receipt_count(&self) -> sails_rs::client::PendingCall<io::ReceiptCount, Self::Env> {
            self.pending_call(())
        }
        fn required_fee(&self) -> sails_rs::client::PendingCall<io::RequiredFee, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Issue (subject: [u8; 32], kind: super::AttestationKind) -> Result<super::Receipt, super::Error>);
        sails_rs::io_struct_impl!(CollectedFees () -> u128);
        sails_rs::io_struct_impl!(ReceiptCount () -> u64);
        sails_rs::io_struct_impl!(RequiredFee () -> u128);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum AttestEvents {
            ReceiptIssued {
                caller: ActorId,
                subject: [u8; 32],
                kind: AttestationKind,
                seq: u64,
                fee_paid: u128,
            },
        }
        impl sails_rs::client::Event for AttestEvents {
            const EVENT_NAMES: &'static [Route] = &["ReceiptIssued"];
        }
        impl sails_rs::client::ServiceWithEvents for AttestImpl {
            type Event = AttestEvents;
        }
    }
}
/// Caller-supplied attestation type. Closed enum (additive-only post-v1).
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum AttestationKind {
    /// Generic proof-of-action receipt.
    Action,
    /// Identity check receipt.
    Identity,
    /// Custom domain receipt — the caller's `subject` carries semantics.
    Custom,
}
/// Sequence-numbered attestation. Stable across retries once we add dedupe.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Receipt {
    pub seq: u64,
    pub caller: ActorId,
    pub subject: [u8; 32],
    pub kind: AttestationKind,
    pub fee_paid: u128,
    pub issued_at: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Error {
    /// Owner-gated method called by a non-owner. Reserved for SetFee /
    /// WithdrawFees (next iteration).
    Unauthorized,
    /// `msg::value()` was less than `required_fee()`.
    InsufficientPayment,
    /// Self-loop attempt: program calling itself. Receiver-side anti-cheat per
    /// `agent-starter/references/pricing.md`.
    SelfLoop,
    /// Counter overflow — `next_seq` or `collected_fees` would wrap. Practically
    /// unreachable for any realistic fee/call volume but enumerated so callers
    /// see a typed error instead of a panic if it ever does.
    ArithmeticOverflow,
}
