// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct FactoryClientProgram;
impl sails_rs::client::Program for FactoryClientProgram {}
pub trait FactoryClient {
    type Env: sails_rs::client::GearEnv;
    fn deployer(&self) -> sails_rs::client::Service<deployer::DeployerImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> FactoryClient
    for sails_rs::client::Actor<FactoryClientProgram, E>
{
    type Env = E;
    fn deployer(&self) -> sails_rs::client::Service<deployer::DeployerImpl, Self::Env> {
        self.service(stringify!(Deployer))
    }
}
pub trait FactoryClientCtors {
    type Env: sails_rs::client::GearEnv;
    /// `admin` controls cooldown updates and admin transfer. If
    /// `cooldown_blocks` is `None`, `DEFAULT_COOLDOWN_BLOCKS` is used.
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        admin: ActorId,
        cooldown_blocks: Option<u32>,
    ) -> sails_rs::client::PendingCtor<FactoryClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> FactoryClientCtors
    for sails_rs::client::Deployment<FactoryClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        admin: ActorId,
        cooldown_blocks: Option<u32>,
    ) -> sails_rs::client::PendingCtor<FactoryClientProgram, io::New, Self::Env> {
        self.pending_ctor((admin, cooldown_blocks))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (admin: ActorId, cooldown_blocks: Option<u32>) -> ());
}

pub mod deployer {
    use super::*;
    pub trait Deployer {
        type Env: sails_rs::client::GearEnv;
        /// Deploy a new program from a previously uploaded `code_id`.
        ///
        /// The caller (`msg::source()`) is recorded as the logical deployer.
        /// `msg::source()` of the new program's init handler will be this
        /// factory program — agent programs MUST accept their admin/owner
        /// `ActorId` in `init_payload` rather than reading `msg::source()`.
        ///
        /// `user_salt` controls the deterministic program ID — combined with
        /// the deployer's `ActorId`, it forms the salt passed to the runtime.
        /// Two different deployers passing the same `user_salt` get different
        /// program IDs. The same deployer must vary `user_salt` between deploys
        /// of the same code; otherwise the runtime rejects with `CreateProgramFailed`.
        ///
        /// `init_gas_limit` is the gas budget reserved for the new program's
        /// init handler. The default-gas variant (`create_program_bytes_delayed`)
        /// dispatches init with `gas_limit=0`, which makes any non-trivial init
        /// trap immediately — so we always use the explicit-gas variant. Sails
        /// program inits typically need 2-10 billion gas; pass a generous
        /// `init_gas_limit` to avoid out-of-gas at init time. Capped at
        /// `MAX_INIT_GAS_LIMIT`.
        ///
        /// v1: init `value` is hardcoded to 0 — any program needing init value
        /// must wait for v2.
        fn deploy(
            &mut self,
            code_id: CodeId,
            user_salt: [u8; 16],
            init_payload: Vec<u8>,
            init_gas_limit: u64,
        ) -> sails_rs::client::PendingCall<io::Deploy, Self::Env>;
        /// Set the per-deployer cooldown in blocks. Admin only.
        fn set_cooldown(
            &mut self,
            blocks: u32,
        ) -> sails_rs::client::PendingCall<io::SetCooldown, Self::Env>;
        /// Transfer admin rights. Admin only.
        fn transfer_admin(
            &mut self,
            new_admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::TransferAdmin, Self::Env>;
        fn admin(&self) -> sails_rs::client::PendingCall<io::Admin, Self::Env>;
        fn cooldown(&self) -> sails_rs::client::PendingCall<io::Cooldown, Self::Env>;
        fn last_deploy_block(
            &self,
            deployer: ActorId,
        ) -> sails_rs::client::PendingCall<io::LastDeployBlock, Self::Env>;
        /// First block at which `deployer` may deploy again. If the deployer
        /// has never deployed, returns 0.
        fn next_eligible_block(
            &self,
            deployer: ActorId,
        ) -> sails_rs::client::PendingCall<io::NextEligibleBlock, Self::Env>;
        fn total_deploys(&self) -> sails_rs::client::PendingCall<io::TotalDeploys, Self::Env>;
    }
    pub struct DeployerImpl;
    impl<E: sails_rs::client::GearEnv> Deployer for sails_rs::client::Service<DeployerImpl, E> {
        type Env = E;
        fn deploy(
            &mut self,
            code_id: CodeId,
            user_salt: [u8; 16],
            init_payload: Vec<u8>,
            init_gas_limit: u64,
        ) -> sails_rs::client::PendingCall<io::Deploy, Self::Env> {
            self.pending_call((code_id, user_salt, init_payload, init_gas_limit))
        }
        fn set_cooldown(
            &mut self,
            blocks: u32,
        ) -> sails_rs::client::PendingCall<io::SetCooldown, Self::Env> {
            self.pending_call((blocks,))
        }
        fn transfer_admin(
            &mut self,
            new_admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::TransferAdmin, Self::Env> {
            self.pending_call((new_admin,))
        }
        fn admin(&self) -> sails_rs::client::PendingCall<io::Admin, Self::Env> {
            self.pending_call(())
        }
        fn cooldown(&self) -> sails_rs::client::PendingCall<io::Cooldown, Self::Env> {
            self.pending_call(())
        }
        fn last_deploy_block(
            &self,
            deployer: ActorId,
        ) -> sails_rs::client::PendingCall<io::LastDeployBlock, Self::Env> {
            self.pending_call((deployer,))
        }
        fn next_eligible_block(
            &self,
            deployer: ActorId,
        ) -> sails_rs::client::PendingCall<io::NextEligibleBlock, Self::Env> {
            self.pending_call((deployer,))
        }
        fn total_deploys(&self) -> sails_rs::client::PendingCall<io::TotalDeploys, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Deploy (code_id: CodeId, user_salt: [u8; 16], init_payload: Vec<u8>, init_gas_limit: u64) -> ActorId);
        sails_rs::io_struct_impl!(SetCooldown (blocks: u32) -> ());
        sails_rs::io_struct_impl!(TransferAdmin (new_admin: ActorId) -> ());
        sails_rs::io_struct_impl!(Admin () -> ActorId);
        sails_rs::io_struct_impl!(Cooldown () -> u32);
        sails_rs::io_struct_impl!(LastDeployBlock (deployer: ActorId) -> Option<u32>);
        sails_rs::io_struct_impl!(NextEligibleBlock (deployer: ActorId) -> u32);
        sails_rs::io_struct_impl!(TotalDeploys () -> u64);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum DeployerEvents {
            /// A program was successfully created. Init message is in flight at
            /// emit time; subscribers should watch `program_id` for its init reply
            /// to know whether init succeeded.
            ProgramDeployed {
                deployer: ActorId,
                code_id: CodeId,
                program_id: ActorId,
                init_msg_id: MessageId,
                block: u32,
            },
            /// Admin transferred. Emitted by `transfer_admin`.
            AdminTransferred {
                old_admin: ActorId,
                new_admin: ActorId,
            },
            /// Cooldown updated. Emitted by `set_cooldown`.
            CooldownUpdated { old: u32, new: u32 },
        }
        impl sails_rs::client::Event for DeployerEvents {
            const EVENT_NAMES: &'static [Route] =
                &["ProgramDeployed", "AdminTransferred", "CooldownUpdated"];
        }
        impl sails_rs::client::ServiceWithEvents for DeployerImpl {
            type Event = DeployerEvents;
        }
    }
}
