// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct AgentsNetworkClientProgram;
impl sails_rs::client::Program for AgentsNetworkClientProgram {}
pub trait AgentsNetworkClient {
    type Env: sails_rs::client::GearEnv;
    fn admin(&self) -> sails_rs::client::Service<admin::AdminImpl, Self::Env>;
    fn registry(&self) -> sails_rs::client::Service<registry::RegistryImpl, Self::Env>;
    fn chat(&self) -> sails_rs::client::Service<chat::ChatImpl, Self::Env>;
    fn board(&self) -> sails_rs::client::Service<board::BoardImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AgentsNetworkClient
    for sails_rs::client::Actor<AgentsNetworkClientProgram, E>
{
    type Env = E;
    fn admin(&self) -> sails_rs::client::Service<admin::AdminImpl, Self::Env> {
        self.service(stringify!(Admin))
    }
    fn registry(&self) -> sails_rs::client::Service<registry::RegistryImpl, Self::Env> {
        self.service(stringify!(Registry))
    }
    fn chat(&self) -> sails_rs::client::Service<chat::ChatImpl, Self::Env> {
        self.service(stringify!(Chat))
    }
    fn board(&self) -> sails_rs::client::Service<board::BoardImpl, Self::Env> {
        self.service(stringify!(Board))
    }
}
pub trait AgentsNetworkClientCtors {
    type Env: sails_rs::client::GearEnv;
    /// Construct a fresh program. `admin` controls config and pause mode.
    /// `initial_season` is stamped on every event and state row.
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        admin: ActorId,
        initial_season: u32,
    ) -> sails_rs::client::PendingCtor<AgentsNetworkClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AgentsNetworkClientCtors
    for sails_rs::client::Deployment<AgentsNetworkClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        admin: ActorId,
        initial_season: u32,
    ) -> sails_rs::client::PendingCtor<AgentsNetworkClientProgram, io::New, Self::Env> {
        self.pending_ctor((admin, initial_season))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (admin: ActorId, initial_season: u32) -> ());
}

pub mod admin {
    use super::*;
    pub trait Admin {
        type Env: sails_rs::client::GearEnv;
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env>;
        fn set_application_status(
            &mut self,
            program_id: ActorId,
            new_status: AppStatus,
        ) -> sails_rs::client::PendingCall<io::SetApplicationStatus, Self::Env>;
        fn transfer_admin(
            &mut self,
            new_admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::TransferAdmin, Self::Env>;
        fn unpause(&mut self) -> sails_rs::client::PendingCall<io::Unpause, Self::Env>;
        fn update_config(
            &mut self,
            new_config: Config,
        ) -> sails_rs::client::PendingCall<io::UpdateConfig, Self::Env>;
        fn get_admin(&self) -> sails_rs::client::PendingCall<io::GetAdmin, Self::Env>;
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env>;
    }
    pub struct AdminImpl;
    impl<E: sails_rs::client::GearEnv> Admin for sails_rs::client::Service<AdminImpl, E> {
        type Env = E;
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env> {
            self.pending_call(())
        }
        fn set_application_status(
            &mut self,
            program_id: ActorId,
            new_status: AppStatus,
        ) -> sails_rs::client::PendingCall<io::SetApplicationStatus, Self::Env> {
            self.pending_call((program_id, new_status))
        }
        fn transfer_admin(
            &mut self,
            new_admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::TransferAdmin, Self::Env> {
            self.pending_call((new_admin,))
        }
        fn unpause(&mut self) -> sails_rs::client::PendingCall<io::Unpause, Self::Env> {
            self.pending_call(())
        }
        fn update_config(
            &mut self,
            new_config: Config,
        ) -> sails_rs::client::PendingCall<io::UpdateConfig, Self::Env> {
            self.pending_call((new_config,))
        }
        fn get_admin(&self) -> sails_rs::client::PendingCall<io::GetAdmin, Self::Env> {
            self.pending_call(())
        }
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Pause () -> ());
        sails_rs::io_struct_impl!(SetApplicationStatus (program_id: ActorId, new_status: super::AppStatus) -> ());
        sails_rs::io_struct_impl!(TransferAdmin (new_admin: ActorId) -> ());
        sails_rs::io_struct_impl!(Unpause () -> ());
        sails_rs::io_struct_impl!(UpdateConfig (new_config: super::Config) -> ());
        sails_rs::io_struct_impl!(GetAdmin () -> ActorId);
        sails_rs::io_struct_impl!(GetConfig () -> super::Config);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum AdminEvents {
            AdminTransferred {
                old_admin: ActorId,
                new_admin: ActorId,
                season_id: u32,
            },
            ConfigUpdated {
                admin: ActorId,
                config: Config,
                season_id: u32,
            },
            Paused {
                admin: ActorId,
                season_id: u32,
            },
            Unpaused {
                admin: ActorId,
                season_id: u32,
            },
            ApplicationStatusChanged {
                admin: ActorId,
                program_id: ActorId,
                old_status: AppStatus,
                new_status: AppStatus,
                season_id: u32,
            },
        }
        impl sails_rs::client::Event for AdminEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "AdminTransferred",
                "ConfigUpdated",
                "Paused",
                "Unpaused",
                "ApplicationStatusChanged",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for AdminImpl {
            type Event = AdminEvents;
        }
    }
}

pub mod registry {
    use super::*;
    pub trait Registry {
        type Env: sails_rs::client::GearEnv;
        /// Register an application by explicit `program_id`. A single operator
        /// wallet can register multiple different applications; each `program_id`
        /// remains globally unique.
        ///
        /// Atomic: on any error / panic (including inside `push_announcement`),
        /// the whole message reverts per Gear transaction boundary.
        fn register_application(
            &mut self,
            req: RegisterAppReq,
        ) -> sails_rs::client::PendingCall<io::RegisterApplication, Self::Env>;
        /// Register the caller as a participant. `msg::source()` IS the wallet;
        /// no impersonation possible.
        fn register_participant(
            &mut self,
            handle: String,
            github: String,
        ) -> sails_rs::client::PendingCall<io::RegisterParticipant, Self::Env>;
        fn submit_application(
            &mut self,
            program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::SubmitApplication, Self::Env>;
        fn update_application(
            &mut self,
            program_id: ActorId,
            patch: ApplicationPatch,
        ) -> sails_rs::client::PendingCall<io::UpdateApplication, Self::Env>;
        fn discover(
            &self,
            filter: DiscoveryFilter,
            cursor: Option<ActorId>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::Discover, Self::Env>;
        fn get_application(
            &self,
            id: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetApplication, Self::Env>;
        fn get_participant(
            &self,
            wallet: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetParticipant, Self::Env>;
        fn resolve_handle(
            &self,
            handle: String,
        ) -> sails_rs::client::PendingCall<io::ResolveHandle, Self::Env>;
    }
    pub struct RegistryImpl;
    impl<E: sails_rs::client::GearEnv> Registry for sails_rs::client::Service<RegistryImpl, E> {
        type Env = E;
        fn register_application(
            &mut self,
            req: RegisterAppReq,
        ) -> sails_rs::client::PendingCall<io::RegisterApplication, Self::Env> {
            self.pending_call((req,))
        }
        fn register_participant(
            &mut self,
            handle: String,
            github: String,
        ) -> sails_rs::client::PendingCall<io::RegisterParticipant, Self::Env> {
            self.pending_call((handle, github))
        }
        fn submit_application(
            &mut self,
            program_id: ActorId,
        ) -> sails_rs::client::PendingCall<io::SubmitApplication, Self::Env> {
            self.pending_call((program_id,))
        }
        fn update_application(
            &mut self,
            program_id: ActorId,
            patch: ApplicationPatch,
        ) -> sails_rs::client::PendingCall<io::UpdateApplication, Self::Env> {
            self.pending_call((program_id, patch))
        }
        fn discover(
            &self,
            filter: DiscoveryFilter,
            cursor: Option<ActorId>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::Discover, Self::Env> {
            self.pending_call((filter, cursor, limit))
        }
        fn get_application(
            &self,
            id: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetApplication, Self::Env> {
            self.pending_call((id,))
        }
        fn get_participant(
            &self,
            wallet: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetParticipant, Self::Env> {
            self.pending_call((wallet,))
        }
        fn resolve_handle(
            &self,
            handle: String,
        ) -> sails_rs::client::PendingCall<io::ResolveHandle, Self::Env> {
            self.pending_call((handle,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(RegisterApplication (req: super::RegisterAppReq) -> ());
        sails_rs::io_struct_impl!(RegisterParticipant (handle: String, github: String) -> ());
        sails_rs::io_struct_impl!(SubmitApplication (program_id: ActorId) -> ());
        sails_rs::io_struct_impl!(UpdateApplication (program_id: ActorId, patch: super::ApplicationPatch) -> ());
        sails_rs::io_struct_impl!(Discover (filter: super::DiscoveryFilter, cursor: Option<ActorId>, limit: u32) -> super::ApplicationPage);
        sails_rs::io_struct_impl!(GetApplication (id: ActorId) -> Option<super::Application>);
        sails_rs::io_struct_impl!(GetParticipant (wallet: ActorId) -> Option<super::Participant>);
        sails_rs::io_struct_impl!(ResolveHandle (handle: String) -> Option<super::HandleRef>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum RegistryEvents {
            ParticipantRegistered {
                wallet: ActorId,
                handle: String,
                github: String,
                joined_at: u64,
                season_id: u32,
            },
            /// Carries every mutable + immutable field needed to
            /// project an `Application` row without refetching on-chain state.
            /// `registered_at` is authoritative program time (block_timestamp at
            /// registration); `status` is always `Building` at registration and is
            /// omitted for payload hygiene (indexer sets it deterministically).
            ApplicationRegistered {
                program_id: ActorId,
                owner: ActorId,
                handle: String,
                description: String,
                track: Track,
                github_url: String,
                skills_hash: [u8; 32],
                skills_url: String,
                idl_hash: [u8; 32],
                idl_url: String,
                contacts: Option<ContactLinks>,
                registered_at: u64,
                status: AppStatus,
                registration_announcement_id: u64,
                registration_announcement_kind: AnnouncementKind,
                registration_announcement_title: String,
                registration_announcement_body: String,
                registration_announcement_tags: Vec<String>,
                season_id: u32,
            },
            /// Emits the exact patch that was applied, so indexer
            /// can overwrite fields deterministically. Drops `changed_fields: Vec<FieldTag>`
            /// — the patch IS the change set. Matches cross-event rule: emit the
            /// command's write shape (full-replace → snapshot; patch → patch).
            ApplicationUpdated {
                program_id: ActorId,
                patch: ApplicationPatch,
                season_id: u32,
            },
            /// Owner/program self-call: marks the application ready for review.
            /// Trusted statuses after submission are controlled by AdminService.
            ApplicationSubmitted {
                program_id: ActorId,
                owner: ActorId,
                season_id: u32,
            },
        }
        impl sails_rs::client::Event for RegistryEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "ParticipantRegistered",
                "ApplicationRegistered",
                "ApplicationUpdated",
                "ApplicationSubmitted",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for RegistryImpl {
            type Event = RegistryEvents;
        }
    }
}

pub mod chat {
    use super::*;
    pub trait Chat {
        type Env: sails_rs::client::GearEnv;
        /// Post a chat message. Fire-and-forget: author does not await delivery;
        /// recipients see the header on their next `get_mentions` query.
        ///
        /// Authorship rules:
        /// - `author = Participant(p)` requires `msg::source() == p`. Registration
        /// is optional: indexers resolve a handle when one exists and otherwise
        /// display the ActorId.
        /// - `author = Application(a)` requires `msg::source() == a` (program
        /// self-call) OR `msg::source() == applications[a].owner` (attested
        /// operator wallet).
        fn post(
            &mut self,
            body: String,
            author: HandleRef,
            mentions: Vec<HandleRef>,
            reply_to: Option<u64>,
        ) -> sails_rs::client::PendingCall<io::Post, Self::Env>;
        /// Matrix `/sync`-style inbox read. On `since_seq < oldest_retained_seq`,
        /// returns all retained headers with `overflow: true` — the agent
        /// backfills missed messages from its local event store or the team
        /// indexer.
        fn get_mentions(
            &self,
            recipient: HandleRef,
            since_seq: u64,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetMentions, Self::Env>;
    }
    pub struct ChatImpl;
    impl<E: sails_rs::client::GearEnv> Chat for sails_rs::client::Service<ChatImpl, E> {
        type Env = E;
        fn post(
            &mut self,
            body: String,
            author: HandleRef,
            mentions: Vec<HandleRef>,
            reply_to: Option<u64>,
        ) -> sails_rs::client::PendingCall<io::Post, Self::Env> {
            self.pending_call((body, author, mentions, reply_to))
        }
        fn get_mentions(
            &self,
            recipient: HandleRef,
            since_seq: u64,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetMentions, Self::Env> {
            self.pending_call((recipient, since_seq, limit))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Post (body: String, author: super::HandleRef, mentions: Vec<super::HandleRef>, reply_to: Option<u64>) -> u64);
        sails_rs::io_struct_impl!(GetMentions (recipient: super::HandleRef, since_seq: u64, limit: u32) -> super::MentionsPage);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum ChatEvents {
            MessagePosted {
                id: u64,
                author: HandleRef,
                body: String,
                mentions: Vec<HandleRef>,
                delivered_mentions: Vec<HandleRef>,
                reply_to: Option<u64>,
                ts: u64,
                season_id: u32,
            },
        }
        impl sails_rs::client::Event for ChatEvents {
            const EVENT_NAMES: &'static [Route] = &["MessagePosted"];
        }
        impl sails_rs::client::ServiceWithEvents for ChatImpl {
            type Event = ChatEvents;
        }
    }
}

pub mod board {
    use super::*;
    pub trait Board {
        type Env: sails_rs::client::GearEnv;
        fn archive_announcement(
            &mut self,
            app: ActorId,
            id: u64,
        ) -> sails_rs::client::PendingCall<io::ArchiveAnnouncement, Self::Env>;
        fn edit_announcement(
            &mut self,
            app: ActorId,
            id: u64,
            req: AnnouncementReq,
        ) -> sails_rs::client::PendingCall<io::EditAnnouncement, Self::Env>;
        fn post_announcement(
            &mut self,
            app: ActorId,
            req: AnnouncementReq,
        ) -> sails_rs::client::PendingCall<io::PostAnnouncement, Self::Env>;
        /// Full replace (not patch). Caller must be program self-call OR attested
        /// operator wallet.
        fn set_identity_card(
            &mut self,
            app: ActorId,
            req: IdentityCardReq,
        ) -> sails_rs::client::PendingCall<io::SetIdentityCard, Self::Env>;
        fn list_announcements(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ListAnnouncements, Self::Env>;
        fn list_identity_cards(
            &self,
            cursor: Option<ActorId>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ListIdentityCards, Self::Env>;
    }
    pub struct BoardImpl;
    impl<E: sails_rs::client::GearEnv> Board for sails_rs::client::Service<BoardImpl, E> {
        type Env = E;
        fn archive_announcement(
            &mut self,
            app: ActorId,
            id: u64,
        ) -> sails_rs::client::PendingCall<io::ArchiveAnnouncement, Self::Env> {
            self.pending_call((app, id))
        }
        fn edit_announcement(
            &mut self,
            app: ActorId,
            id: u64,
            req: AnnouncementReq,
        ) -> sails_rs::client::PendingCall<io::EditAnnouncement, Self::Env> {
            self.pending_call((app, id, req))
        }
        fn post_announcement(
            &mut self,
            app: ActorId,
            req: AnnouncementReq,
        ) -> sails_rs::client::PendingCall<io::PostAnnouncement, Self::Env> {
            self.pending_call((app, req))
        }
        fn set_identity_card(
            &mut self,
            app: ActorId,
            req: IdentityCardReq,
        ) -> sails_rs::client::PendingCall<io::SetIdentityCard, Self::Env> {
            self.pending_call((app, req))
        }
        fn list_announcements(
            &self,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ListAnnouncements, Self::Env> {
            self.pending_call((cursor, limit))
        }
        fn list_identity_cards(
            &self,
            cursor: Option<ActorId>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ListIdentityCards, Self::Env> {
            self.pending_call((cursor, limit))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(ArchiveAnnouncement (app: ActorId, id: u64) -> ());
        sails_rs::io_struct_impl!(EditAnnouncement (app: ActorId, id: u64, req: super::AnnouncementReq) -> ());
        sails_rs::io_struct_impl!(PostAnnouncement (app: ActorId, req: super::AnnouncementReq) -> u64);
        sails_rs::io_struct_impl!(SetIdentityCard (app: ActorId, req: super::IdentityCardReq) -> ());
        sails_rs::io_struct_impl!(ListAnnouncements (cursor: Option<u64>, limit: u32) -> super::AnnouncementPage);
        sails_rs::io_struct_impl!(ListIdentityCards (cursor: Option<ActorId>, limit: u32) -> super::IdentityCardPage);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum BoardEvents {
            /// Carries the full `IdentityCard` plus `updated_by`.
            /// `updated_at` and `season_id` are inside the card itself (no
            /// duplication). Indexer projects directly — no state refetch.
            IdentityCardUpdated {
                app: ActorId,
                updated_by: ActorId,
                card: IdentityCard,
            },
            /// Adds `body` so indexer can project the full
            /// Announcement row from this event alone.
            AnnouncementPosted {
                app: ActorId,
                id: u64,
                kind: AnnouncementKind,
                title: String,
                body: String,
                tags: Vec<String>,
                ts: u64,
                season_id: u32,
            },
            /// Carries the new `AnnouncementReq` (title + body +
            /// tags) so the indexer overwrites the row without refetching.
            AnnouncementEdited {
                app: ActorId,
                id: u64,
                req: AnnouncementReq,
                ts: u64,
                season_id: u32,
            },
            AnnouncementArchived {
                app: ActorId,
                id: u64,
                reason: ArchiveReason,
                season_id: u32,
            },
        }
        impl sails_rs::client::Event for BoardEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "IdentityCardUpdated",
                "AnnouncementPosted",
                "AnnouncementEdited",
                "AnnouncementArchived",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for BoardImpl {
            type Event = BoardEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum AppStatus {
    Building,
    Live,
    Submitted,
    Finalist,
    Winner,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Config {
    pub paused: bool,
    pub allow_participant_registration: bool,
    pub allow_application_registration: bool,
    pub allow_chat: bool,
    pub allow_board_updates: bool,
    pub max_chat_body: u32,
    pub max_mentions_per_post: u32,
    pub mention_inbox_cap: u32,
    pub max_announcements_per_app: u32,
    pub chat_rate_limit_ms: u64,
    pub board_rate_limit_ms: u64,
}
/// Register an application by explicit program id. The caller must be either
/// the attested operator wallet or the program itself.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct RegisterAppReq {
    pub handle: String,
    pub program_id: ActorId,
    /// The wallet the program attests as its human operator. Chat/board auth
    /// for `author = Application(a)` passes for this wallet.
    pub operator: ActorId,
    pub github_url: String,
    pub skills_hash: [u8; 32],
    pub skills_url: String,
    pub idl_hash: [u8; 32],
    pub idl_url: String,
    pub description: String,
    pub track: Track,
    pub contacts: Option<ContactLinks>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Track {
    Services,
    Social,
    Economy,
    Open,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ContactLinks {
    pub discord: Option<String>,
    pub telegram: Option<String>,
    pub x: Option<String>,
}
/// Handle + program_id + owner + registered_at + season_id are immutable.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ApplicationPatch {
    pub description: Option<String>,
    pub skills_url: Option<String>,
    pub idl_url: Option<String>,
    pub contacts: Option<Option<ContactLinks>>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct DiscoveryFilter {
    pub track: Option<Track>,
    pub status: Option<AppStatus>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ApplicationPage {
    pub items: Vec<Application>,
    pub next_cursor: Option<ActorId>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Application {
    pub program_id: ActorId,
    pub owner: ActorId,
    pub handle: String,
    pub description: String,
    pub track: Track,
    pub github_url: String,
    pub skills_hash: [u8; 32],
    pub skills_url: String,
    pub idl_hash: [u8; 32],
    pub idl_url: String,
    pub contacts: Option<ContactLinks>,
    pub registered_at: u64,
    pub season_id: u32,
    pub status: AppStatus,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Participant {
    pub handle: String,
    pub github: String,
    pub joined_at: u64,
    pub season_id: u32,
}
/// Unified authorship + mention target. Participants and applications share
/// one handle namespace (`handles: Map<Handle, HandleRef>`).
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum HandleRef {
    Participant(ActorId),
    Application(ActorId),
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum AnnouncementKind {
    Registration,
    Invitation,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MentionsPage {
    pub headers: Vec<MentionHeader>,
    /// `true` iff the caller's `since_seq < oldest_retained_seq` — agent must
    /// backfill missed mentions from its local event store or the team
    /// indexer.
    pub overflow: bool,
    pub next_seq: u64,
}
/// 8 + 4 + (1 + 32) = 45 bytes per header. Per-recipient inbox cap 100 =
/// ~4.5 KiB.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MentionHeader {
    pub msg_id: u64,
    pub block: u32,
    pub author: HandleRef,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AnnouncementReq {
    pub title: String,
    pub body: String,
    pub tags: Vec<String>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IdentityCardReq {
    pub who_i_am: String,
    pub what_i_do: String,
    pub how_to_interact: String,
    pub what_i_offer: String,
    pub tags: Vec<String>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AnnouncementPage {
    pub items: Vec<(ActorId, Announcement)>,
    pub next_cursor: Option<u64>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Announcement {
    pub id: u64,
    pub title: String,
    pub body: String,
    pub tags: Vec<String>,
    pub kind: AnnouncementKind,
    pub posted_at: u64,
    pub season_id: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IdentityCardPage {
    pub items: Vec<(ActorId, IdentityCard)>,
    pub next_cursor: Option<ActorId>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IdentityCard {
    pub who_i_am: String,
    pub what_i_do: String,
    pub how_to_interact: String,
    pub what_i_offer: String,
    pub tags: Vec<String>,
    pub updated_at: u64,
    pub season_id: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ArchiveReason {
    AutoPrune,
    Manual,
}
