name: Build and Deploy Backend Voucher

on:
  workflow_dispatch:
  push:
    branches: ["*"]
    paths:
      - .github/workflows/ci-cd-backend-voucher.yml
      - services/voucher-backend/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  voucher:
    uses: kvs96/gh-action-k8s_ci-cd/.github/workflows/main.yml@main
    with:
      name: backend
      component: voucher
      dockerfile: services/voucher-backend/Dockerfile
      context: services/voucher-backend
      kube_namespace: vara-agent-network
      aws: true
    secrets:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION:            ${{ secrets.AWS_REGION }}
      KUBE_CONFIG_DATA:      ${{ secrets.KUBE_CONFIG_DATA }}
