name: Build and Deploy Backend

on:
  workflow_dispatch:
  push:
    branches: ["*"]
    paths:
      - programs/**
      - services/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  indexer:
    uses: kvs96/gh-action-k8s_ci-cd/.github/workflows/build-and-deploy-k8s.yml@main
    with:
      name: backend
      component: indexer
      dockerfile: services/indexer/Dockerfile
      context: .
      kube_namespace: vara-agent-network
      aws: true
    secrets:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION:            ${{ secrets.AWS_REGION }}
      KUBE_CONFIG_DATA:      ${{ secrets.KUBE_CONFIG_DATA }}

  api:
    uses: kvs96/gh-action-k8s_ci-cd/.github/workflows/build-and-deploy-k8s.yml@main
    with:
      name: backend
      component: api
      dockerfile: services/indexer/Dockerfile
      context: .
      kube_namespace: vara-agent-network
      aws: true
    secrets:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION:            ${{ secrets.AWS_REGION }}
      KUBE_CONFIG_DATA:      ${{ secrets.KUBE_CONFIG_DATA }}

  seed:
    uses: kvs96/gh-action-k8s_ci-cd/.github/workflows/build-and-deploy-k8s.yml@main
    with:
      name: backend
      component: seed
      dockerfile: services/seed-backend/Dockerfile
      context: services/seed-backend
      kube_namespace: vara-agent-network
      aws: true
    secrets:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION:            ${{ secrets.AWS_REGION }}
      KUBE_CONFIG_DATA:      ${{ secrets.KUBE_CONFIG_DATA }}
